linters:
  DuplicateProperty:
    enabled: false
  LeadingZero:
    style: include_zero
  MergeableSelector:
    enabled: false
  PropertySortOrder:
    enabled: false
  UrlFormat:
    enabled: false
