default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: page_development

test:
  <<: *default
  database: page_test

production:
  <<: *default
  database: page_production
  username: root
  password: <%= ENV['PAGE_DATABASE_PASSWORD'] %>
