default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: content_development

test:
  <<: *default
  database: content_test

production:
  <<: *default
  database: content_production
  username: content
  password: <%= ENV['CONTENT_DATABASE_PASSWORD'] %>
